### ISSUE TITLE
Printer gets stuck same place

### ISSUE THREAD

**Issue by peidof** [hillsoftware/sv06#10]
Hi Michael im using your V60 version and im getting this on some long prints... it is random but normally starts on the first layers

https://photos.app.goo.gl/8SH8PFwptwQCTpRRA

tried different slicers ,im going to try and downgrade and see if it is the same or not

**Comment by hillsoftware** [comment]
Are you printing from SD or sending g-code over USB with PC, Pi, etc?

**Comment by hillsoftware** [comment]
Also if you have it on (and probably do) try disabling linear advance on one of your problem prints and see if it gets past the problem area.  Hopefully you have a problem print that has the area quick enough to not waste too much plastic.

**Comment by peidof** [comment]
i print from sd card , it's not the orignal one its a sandisk ,i will test it later today and i will let you know thanks :)

i will try disabling linear advance from the menu and then i will try as well adding  M900 K0 to the gcode

**Comment by peidof** [comment]
I think I've found the issue and it was a piece of plastic stuck ok the extruder :/ I think I will need to buy a new one now
