### ISSUE TITLE
#define SPEAKER macro

### ISSUE THREAD

**Issue by quantumfrost** [hillsoftware/sv06#13]
In the stock SV06 firmware source, they have `#define SPEAKER` in `Configuration.h` which allows for producing tones of different frequencies. The hardware is capable of it, so I don't see a reason to have it disabled.

**Comment by CWO4** [comment]
Here's a guess.  Some people run these in their home in places where random beeps, whistles, and random Things That Go Clunk In The Night at 3AM would not be appreciated.  But that's just my WAG.

**Comment by csdabral-ncsu** [comment]
> Here's a guess. Some people run these in their home in places where random beeps, whistles, and random Things That Go Clunk In The Night at 3AM would not be appreciated. But that's just my WAG.

The sounds are still enabled (and can be turned off). The `SPEAKER` macro just allows producing different frequencies.

> The speaker is disabled in the configuration because of crash issues it causes with the clone processor used in the Sovol.

I see, thanks.
