### ISSUE TITLE
Blank blue screen after flashing firmware

### ISSUE THREAD

**Issue by Stewmath** [hillsoftware/sv06#15]
I tried flashing v57-bilinear to my printer (md5: 174be5a7b1b0b2d0cb11138c405910e7), and now my printer doesn't seem to do anything. Blank blue screen on the LCD. This is despite having done a firmware upgrade before with the official firmware.

I've tried every trick I could find on the internet to try and get the old firmware back, but nothing seems to work. I tried like 5 SD cards ranging from 2gb to 16gb capacity, reformatted them, tried cluster size 2048 and 4096, mbr and gpt, different filenames for the firmware every time, different partition sizes... nothing works. No response from the printer.

I'm guessing that there must be some way to flash a firmware via an arduino or something, which I'm prepared to do if I need to, once I find some documentation on how that works. Though I'm still hoping for some magic trick to make the SD card hit just right =)

**Comment by j-lang** [comment]
Had a similar effect, every firmware update went wrong as you described here. My mistake was to use the usb-sd adapter delivered with the printer. I tried to copy the firmware file with another cardreader and it worked. "Save eject" before inserting in the printer made no difference (This was for a firmware update problem on a Bigtree board in an other 3d-printer)
Compared the firmware files on the sdcard an they where identically. 
From Sovol manual: Make sure the card is formatted fat32 with 4096 allocation size.

**Comment by hillsoftware** [comment]
Make sure you keep renaming the bin file to something small and unique. Like bart.bin , homer.bin etc as you try different FAT32 formatted SD cards. The board is very finicky (probably because of the clone processor).  Some people have had to go through a ton of SD cards before they could get the bootloader to do the upgrade.

I would assume you could use an arduino to do it, you can definitely use an ST Link V2 to do it also. You just want to be very careful you don't overwrite or erase the bootloader part of the flash.

Closing this as it isn't bug related to the Marlin build, rather an issue with the board.

**Comment by Stewmath** [comment]
Different SD card readers don't seem to make a difference, unfortunately, and I've definitely tried shorter names but I'll keep doing that anyway. Tried formatting it on windows instead of linux too. No change so far. If this isn't bricked then it's doing an amazing job at pretending to be.

**Comment by hillsoftware** [comment]
The bootloader is stored in the first 28K of memory and doesn't get erased by the bootloader flash code when you flash whatever version of Marlin you are using. So generally you don't ever brick them.  

One problem someone had was the microSD card adapter was loose from the PCB. It wasn't soldered well. They re-soldered the pins better and they were back in action.  Obviously if that is your issue and you aren't capable at soldering you could just get Sovol to get you a new one.

The bootloader just boots the processor, checks for an SD card and if there is one with a bin file, it compares the filename to the last successful flashed filename.  If no SD or no bin file, it just boots current flashed firmware. If the file names are the same it doesn't flash the firmware and just boots the current firmware.  If it is different it flashes the firmware and then boots it.

**Comment by hillsoftware** [comment]
You can also connect your PC over USB to it and turn it on and see if something like Pronterface or similar program can talk to it. Maybe the display is bad.

I have tried to get the source for the bootloader from Sovol but they have pretty much been silent on getting it.  Would be nice to know if the bootloader in that 28K can actually handle receiving an update over USB, or if it is only off the SD card.

**Comment by Stewmath** [comment]
Thanks for all the suggestions, I appreciate it. In particular I'm glad you clarified about the bootloader since I didn't understand how that worked.

But as it turns out it may not have been an issue with the firmware? I tried opening up the case for the main board, unplugging a few wires and plugging them back in... and now it works. I guess something came loose... at the same time as I was flashing a new firmware?

I don't really get it but it's working now. Just setting up the x-twist compensation now, things are looking nicer already!
