### ISSUE TITLE
Probign failed during UBL wizard.

### ISSUE THREAD

**Issue by Dustmuffins** [hillsoftware/sv06#16]
Build 57

As the title says, when the UBL wizard is going, the probe just stays in the same X-Y position, while the Z axis repeatedly probes the same point on the bed, then says probing failed.

**Comment by hillsoftware** [comment]
Try resetting EEPROM or if that doesn't work reflashing (rename the UBL bin file to something different if you go this route so the bootloader actually re-flashes).
