### ISSUE TITLE
Switching to Marlin bugfix instead of this repo?

### ISSUE THREAD

**Issue by kreuzhofer** [hillsoftware/sv06#24]
Hi Michael,

since your board code was recently merged into the bugfix branch of the original Marlin repo, do you think it makes more sense to now work on a example config file for Marlin and post that to the Configurations repo of Marlin?

What is currently different with your fork and the bugfix branch? is it just config files or more?

**Comment by bojanpotocnik** [comment]
So, this means yes or no?

Considering the current state of https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Sovol, we should keep using this repo?

**Comment by hillsoftware** [comment]
The only difference between my version and the main repo is I did some tweaks to the X-Twist and a change to keep the G26 mesh validation in.

I think the mainline Marlin is the best way to go going forward.  I never really cared much for X-Twist as I don't know if it really does much if anything. I think people who use X-Twist might be better suited getting their bed more level and or squaring the frame better. 

I will probably make this repo inactive or whatever github calls it.
