### ISSUE TITLE
Printer Homing Forward on Y Axis

### ISSUE THREAD

**Issue by Kiiiddd** [hillsoftware/sv06#25]
I think the printer is automatically homing to the nearest edge and that doesn't work all that well on the SV06. It will home forward but make a great deal of noise doing it. Any way of forcing the Y Axis to always home to the rear?

**Comment by hillsoftware** [comment]
It homes X to the left and Y to the back.  If you are getting other results I would check the following. 

Is the bed cable being pinched in the back during homing of Y

Your sensorless homing settings.  You can adjust the X and Y values to make it more or less sensitive on homing.

Other than that the other culprit is a bad flash.

**Comment by Kiiiddd** [comment]
Must be a bad flash as I have tested the X and it will home to the right if the head is closer in that direction
