### ISSUE TITLE
I want to use UBL with Sovol SV06, where is Rory's video?

### ISSUE THREAD

**Issue by alber70g** [hillsoftware/sv06#3]
I've got a Sovol SV06 with a warped bed. I'd like to do the UBL. I downloaded this version. 

The readme states:

> **If you downloaded the UBL version follow these steps next**
> Go to Motion / Unified Bed Leveling / UBL Mesh Wizard ( Rory's Video  for info on that)

Where is "Rory's Video"?

**Comment by hillsoftware** [comment]
Removed reference to the video. I don't have a link to it anymore (this was a reference to a video before I put my source on github)

**Comment by hillsoftware** [comment]
Closed
