### ISSUE TITLE
Homing issue

### ISSUE THREAD

**Issue by mshkdm** [hillsoftware/sv06#4]
Hi. Just flashed with v57-UBL. I am trying to do auto homing, and head indeed bumps at x-axis stopper, but then it being pulled by approx. 1cm to the right side and printer starts to think that here is a x home position (which is not, as it is now 1cm away from actual x home position at stock firmware). Not sure about y-axis homing, but i am pretty sure some backward movement happens here also. 
But that's even not the main problem, because Z axis stays about 2cm away from the bed and i can't perform any adjustments in "Config" - "Advanced"- "Set Home offsets" , as i am getting following error message: "Err: too far!"

**Comment by hillsoftware** [comment]
I am not sure exactly what you are trying to indicate. When X homes it will hit the left side of the gantry and then it backs off a tiny bit.  Y does the same thing.  Then it should move so the probe is over the center of the bed.

As for Z after homing, it should lift up to be about 10mm from the bed.  

You should not be doing the set home offset the way you indicate.  You should after homing do a config / advanced / Probe Offsets / Z probe wizard.  And set your Z offset.  It will be around -1 to -2 mm or so.

Then you can do the bed leveling and save everything.

**Comment by mshkdm** [comment]
Well, in my case after hitting the gantry, X backs off by not a tiny bit, but at least 1cm to 1.2cm. This is a completely different behavior from what i observe at stock firmware, where X moves a little bit after hitting, just relieving the pull from motors, as you've said earlier. 
After complete homing nozzle is almost 3 cm off the bed, so i am not able to compensate this distance with z offset, i think. Am i wrong?
Also screen starts to show negative X and Y positions sometimes. I will provide photos of resulting distances of home position and screen data, if you are interested in investigation of this behavior.

**Comment by mshkdm** [comment]
Thank you for the reply. I've managed to set up everything properly after I've watched your video.  Now after UBL set up, with or without X-Twist, first layer adhesion is much better and now i can print not only at bed center, but at 200X200 middle square. However, first layer is not nearly perfect, as my bed is unevenly bent at several places, especially at left side where power cable connected to the heating bed. But i think i'll try flash manual mesh version later, if current results will show not to be sufficient for my goals. 
![ubl_bed_level](https://user-images.githubusercontent.com/19540008/221427052-e54a076a-8011-421a-a53f-beb3053b83ac.jpg)

**Comment by hillsoftware** [comment]
I would look into the silicone insert method  to replace the metal ones under the bed. You can then screw them down differently to get the bed as level as you can.

**Comment by hillsoftware** [comment]
Closed

**Comment by hillsoftware** [comment]
closed
