### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Al3xlol** [hillsoftware/sv06#7]
Filament change gets flagged for no reason

**Comment by hillsoftware** [comment]
Filament detection is disable by default, if you are turning it on you are obviously adding a detection sensor.  If so you may be adding a sensor that has the opposite detection level than the one we coded for.  We look for an active HIGH runout sensor.

This is the tested one https://www.printables.com/model/347596-endstop-runout-sensor

If you are using a sensor that is active low, you need to recompile the code accordingly.
